"use client";

import React, { useRef } from 'react';
import { Customer, Order, getShopSettings } from '@/lib/store';
import { GARMENT_TEMPLATES } from '@/lib/constants';
import * as htmlToImage from 'html-to-image';
import { format, parseISO } from 'date-fns';

interface ReceiptProps {
  order: Order;
  customer: Customer;
  onClose: () => void;
}

export function Receipt({ order, customer, onClose }: ReceiptProps) {
  const receiptRef = useRef<HTMLDivElement>(null);
  const settings = getShopSettings();
  const garment = GARMENT_TEMPLATES.find(g => g.id === order.garmentId);

  const downloadReceipt = async () => {
    if (!receiptRef.current) return;
    try {
      const dataUrl = await htmlToImage.toPng(receiptRef.current, { quality: 1.0 });
      const link = document.createElement('a');
      link.download = `Receipt_${customer.name}_${order.id.substring(0,6)}.png`;
      link.href = dataUrl;
      link.click();
    } catch (err) {
      console.error("Failed to generate receipt image", err);
    }
  };

  const shareReceipt = async () => {
    if (!receiptRef.current) return;
    try {
      const dataUrl = await htmlToImage.toPng(receiptRef.current, { quality: 1.0 });
      const blob = await (await fetch(dataUrl)).blob();
      const file = new File([blob], 'receipt.png', { type: 'image/png' });
      if (navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({
          files: [file],
          title: `Receipt for ${customer.name}`,
        });
      } else {
        alert("Sharing not supported on this browser. Downloading instead.");
        downloadReceipt();
      }
    } catch (err) {
      console.error("Failed to share receipt", err);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/60 z-[100] flex items-center justify-center p-4">
      <div className="bg-white rounded-xl shadow-xl max-w-sm w-full overflow-hidden flex flex-col max-h-[90vh]">
        {/* The actual receipt to capture */}
        <div className="flex-1 overflow-y-auto bg-gray-100 p-4 flex justify-center">
          <div 
            ref={receiptRef} 
            className="bg-white p-6 w-full shadow-sm" 
            style={{ width: '320px', minHeight: '400px' }}
          >
            <div className="text-center border-b border-gray-200 pb-4 mb-4">
              <h2 className="text-2xl font-bold text-[#152A4A]">{settings.shopName}</h2>
              <p className="text-sm text-gray-500">{settings.phone}</p>
              <p className="text-sm text-gray-500">{settings.ownerName}</p>
            </div>
            
            <div className="space-y-2 mb-6">
              <div className="flex justify-between text-sm">
                <span className="text-gray-500">Date:</span>
                <span className="font-medium">{format(parseISO(order.datePlaced), 'dd MMM yyyy')}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-gray-500">Customer:</span>
                <span className="font-bold">{customer.name}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-gray-500">Phone:</span>
                <span className="font-medium">{customer.phone}</span>
              </div>
            </div>

            <div className="border-t border-b border-gray-200 py-3 mb-6 space-y-2">
              <div className="flex justify-between">
                <span className="font-bold text-[#152A4A]">{garment?.name}</span>
                <span className="font-medium">x{order.quantity}</span>
              </div>
              {order.dueDate && (
                <div className="flex justify-between text-sm text-amber-700">
                  <span>Return Date:</span>
                  <span className="font-bold">{format(parseISO(order.dueDate), 'dd MMM yyyy')}</span>
                </div>
              )}
            </div>

            <div className="space-y-1 mb-8">
              <div className="flex justify-between">
                <span className="text-gray-500">Total Amount:</span>
                <span className="font-bold">Rs {order.totalAmount}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-500">Advance Paid:</span>
                <span className="font-medium">Rs {order.amountPaid}</span>
              </div>
              <div className="flex justify-between pt-2 border-t border-gray-100 mt-2">
                <span className="font-bold text-[#152A4A]">Balance:</span>
                <span className="font-bold text-lg text-amber-700">Rs {order.totalAmount - order.amountPaid}</span>
              </div>
            </div>

            <div className="text-center text-xs text-gray-400 mt-8">
              <p>Thank you for choosing us!</p>
              <p>Generated by Tailor Shop Management App</p>
            </div>
          </div>
        </div>

        <div className="p-4 bg-white border-t border-gray-200 flex flex-col gap-2">
          <button 
            onClick={() => {
              import('@/lib/store').then(({ formatWhatsAppNumber, generateWhatsAppMessage }) => {
                const msg = generateWhatsAppMessage('orderPlaced', customer, order, garment?.name || 'Dress', settings);
                const url = `https://wa.me/${formatWhatsAppNumber(customer.phone)}?text=${encodeURIComponent(msg)}`;
                window.open(url, '_blank');
              });
            }}
            className="flex items-center justify-center gap-2 bg-green-50 text-green-700 py-3 rounded-lg font-bold border border-green-200 hover:bg-green-100"
          >
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 21l1.65-3.8a9 9 0 1 1 3.4 2.9l-5.05.9" /><path d="M9 10a.5.5 0 0 0 1 0V9a.5.5 0 0 0-1 0v1a5 5 0 0 0 5 5h1a.5.5 0 0 0 0-1h-1a.5.5 0 0 0 0 1" /></svg>
            Send on WhatsApp
          </button>
          
          <div className="grid grid-cols-2 gap-2">
            <button 
              onClick={shareReceipt}
              className="bg-[#152A4A] text-white py-3 rounded-lg font-bold"
            >
              Share Image
            </button>
            <button 
              onClick={onClose}
              className="bg-gray-100 text-gray-700 py-3 rounded-lg font-bold"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
